name: Submodule Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch event to parent repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}  # Personal Access Token with appropriate repo scope
          repository: aatifbangash/hbv2-controller
          event-type: 'hello_world'
